In [1]:
%load_ext autoreload
%autoreload 2

In [33]:
import os
import tensorflow as tf

import numpy as np
import libspn as spn

from deepsm.graphspn.spn_model import SpnModel, mod_compute_graph_up
from deepsm.graphspn.tbm.spn_template import TemplateSpn, NodeTemplateSpn, EdgeRelationTemplateSpn
from deepsm.graphspn.tbm.spn_instance import NodeTemplateInstanceSpn
from deepsm.graphspn.tbm.template import ThreeRelTemplate, SingleRelTemplate
from deepsm.graphspn.tbm.graph_builder import build_graph
from deepsm.util import CategoryManager

# Load a trained view template SPN

In [87]:
spn_path = "/home/zkytony/Documents/thesis/experiments/deep-semantic-mapping/deepsm/experiments/results/graphspn/EdgeRelationTemplateExperiment/models/ThreeRelTemplate_2_Stockholm456.spn"

In [88]:
sess = tf.Session()

In [89]:
template_spn = EdgeRelationTemplateSpn(ThreeRelTemplate, seed=100)
template_spn.load(spn_path, sess)

[INFO] [spn.JSONLoader:load] Loading SPN graph from file '/home/zkytony/Documents/thesis/experiments/deep-semantic-mapping/deepsm/experiments/results/graphspn/EdgeRelationTemplateExperiment/models/ThreeRelTemplate_2_Stockholm456.spn'


Generating SPN structure...
[Using seed 100]


In [90]:
spn.display_spn_graph(template_spn._root, skip_params=False)

In [91]:
template_spn._root.is_valid()

True

In [92]:
template_spn.template

deepsm.graphspn.tbm.template.ThreeRelTemplate

In [93]:
SpnModel.print_structure(template_spn._root, sess)

Node_8 (Sum)
    Input(Products1/Product1_4, None) (Product)
    Input(Products1/Product2_4, None) (Product)
    Input(Products1/Product3_4, None) (Product)
    Input(Products1/Product4_4, None) (Product)
Products1/Product1_4 (Product)
    Input(Sums1.1/Sum1_2, [0]) (Sum)
    Input(Sums1.2/Sum1_2, [0]) (Sum)
Products1/Product2_4 (Product)
    Input(Sums1.1/Sum2_2, [0]) (Sum)
    Input(Sums1.2/Sum1_2, [0]) (Sum)
Products1/Product3_4 (Product)
    Input(Sums1.1/Sum1_2, [0]) (Sum)
    Input(Sums1.2/Sum2_2, [0]) (Sum)
Products1/Product4_4 (Product)
    Input(Sums1.1/Sum2_2, [0]) (Sum)
    Input(Sums1.2/Sum2_2, [0]) (Sum)
Sums1.1/Sum1_2 (Sum)
    Input(Products2/Product1_2, None) (Product)
    Input(Products2/Product2_2, None) (Product)
    Input(Products2/Product3_2, None) (Product)
    Input(Products2/Product4_2, None) (Product)
    Input(Products2/Product5_2, None) (Product)
    Input(Products2/Product6_2, None) (Product)
    Input(Products2/Product7_2, None) (Product)
    Input(Products

In [94]:
SpnModel.print_weights(template_spn._root, sess)

Node_8 (Sum)
[ 0.03512972  0.89461088  0.03512972  0.03512972] [(4,)]
Sums1.1/Sum1_2 (Sum)
[ 0.09999999  0.09999999  0.09999999  0.09999999  0.09999999  0.09999999
  0.09999999  0.09999999  0.09999999  0.09999999] [(10,)]
Sums1.2/Sum1_2 (Sum)
[ 0.18291855  0.03512972  0.03512972  0.746822  ] [(4,)]
Sums1.1/Sum2_2 (Sum)
[ 0.02901416  0.08528343  0.06450708  0.04892483  0.03940234  0.02901416
  0.27400187  0.18397105  0.140687    0.10519409] [(10,)]
Sums1.2/Sum2_2 (Sum)
[ 0.25  0.25  0.25  0.25] [(4,)]


In [98]:
catg_inputs = spn.IVs(num_vars=3, num_vals=CategoryManager.NUM_CATEGORIES, name="Catg")
view_inputs = spn.IVs(num_vars=1, num_vals=5, name="View")
conc = spn.Concat(catg_inputs, view_inputs)
template_spn._conc_inputs.set_inputs()
copied_tspn_root = mod_compute_graph_up(template_spn._root,
                                        TemplateSpn._dup_fun_up,
                                        tmpl_num_vars=[3, 1],
                                        tmpl_num_vals=[CategoryManager.NUM_CATEGORIES, 5],
                                        graph_num_vars=[catg_inputs.num_vars, view_inputs.num_vars],
                                        conc=conc,
                                        labels=[[0,1,2],[0]])

In [99]:
SpnModel.print_weights(copied_tspn_root, sess)

Sum_33 (Sum)
[ 0.03512972  0.89461088  0.03512972  0.03512972] [(4,)]
Sum_31 (Sum)
[ 0.09999999  0.09999999  0.09999999  0.09999999  0.09999999  0.09999999
  0.09999999  0.09999999  0.09999999  0.09999999] [(10,)]
Sum_32 (Sum)
[ 0.18291855  0.03512972  0.03512972  0.746822  ] [(4,)]
Sum_30 (Sum)
[ 0.02901416  0.08528343  0.06450708  0.04892483  0.03940234  0.02901416
  0.27400187  0.18397105  0.140687    0.10519409] [(10,)]
Sum_29 (Sum)
[ 0.25  0.25  0.25  0.25] [(4,)]


In [100]:
SpnModel.print_structure(copied_tspn_root, sess)

Sum_33 (Sum)
    Input(Product_326, None) (Product)
    Input(Product_325, None) (Product)
    Input(Product_324, None) (Product)
    Input(Product_323, None) (Product)
Product_326 (Product)
    Input(Sum_31, None) (Sum)
    Input(Sum_32, None) (Sum)
Product_325 (Product)
    Input(Sum_30, None) (Sum)
    Input(Sum_32, None) (Sum)
Product_324 (Product)
    Input(Sum_31, None) (Sum)
    Input(Sum_29, None) (Sum)
Product_323 (Product)
    Input(Sum_30, None) (Sum)
    Input(Sum_29, None) (Sum)
Sum_31 (Sum)
    Input(Product_322, None) (Product)
    Input(Product_321, None) (Product)
    Input(Product_320, None) (Product)
    Input(Product_319, None) (Product)
    Input(Product_318, None) (Product)
    Input(Product_317, None) (Product)
    Input(Product_316, None) (Product)
    Input(Product_315, None) (Product)
    Input(Product_314, None) (Product)
    Input(Product_313, None) (Product)
Sum_32 (Sum)
    Input(Product_312, None) (Product)
    Input(Product_311, None) (Product)
    Input

In [101]:
copied_tspn_root.is_valid()

True